project_id = "byipbdumfzuiykkeqezv"

[functions.market-data]
verify_jwt = false

[functions.market-ai]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-rewrite]
verify_jwt = false

[functions.ai-generate-answer]
verify_jwt = false

[functions.ai-convert-link]
verify_jwt = false

[functions.ai-suggest-tags]
verify_jwt = false

[functions.lives]
verify_jwt = false

[functions.search]
verify_jwt = false

[functions.fetch-newsapi-articles]
verify_jwt = false

[functions.news-trending]
verify_jwt = false

[functions.auth-linkedin-connect]
verify_jwt = false

[functions.auth-mobile-request-otp]
verify_jwt = false

[functions.auth-mobile-verify-otp]
verify_jwt = false

[functions.messages-mass]
verify_jwt = false

[functions.promotions-profiles]
verify_jwt = false

[functions.leaderboard-influencers]
verify_jwt = false
